using AIInterviewCoach.Application.Interfaces;

namespace AIInterviewCoach.Infrastructure.Services;

public class MockSpeechToTextService : ISpeechToTextService
{
    public async Task<string> TranscribeAudioAsync(string fileUrl)
    {
        // Simulate API delay
        await Task.Delay(1500);
        return "This is a simulated transcription of the audio file. In a real scenario, this would be generated by OpenAI Whisper.";
    }
}
